[build]
  command = "python manage.py migrate && python manage.py collectstatic --noinput"
  publish = "staticfiles"  # Updated to the correct static directory

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
