[build]
  publish = "staticfiles"
  command = "python manage.py migrate && python manage.py collectstatic --noinput && python manage.py runserver"

# Redirects settings for routing requests to static files
[[redirects]]
  from = "/calculator/*"
  to = "calculator.html"  # Ensure this path matches the static location
  status = 200

[[redirects]]
  from = "/weather/*"
  to = "weather.html"  # Ensure this path matches the static location
  status = 200