[build]
  # The command to run when deploying. 
  command = "python manage.py migrate && python manage.py collectstatic --noinput"  # Run migrations and collect static files
  publish = "staticfiles"  # Publish collected static files to the `staticfiles` folder
  
# Redirects settings for routing requests to the static files
[[redirects]]
  from = "/calculator/*"
  to = "/calculator/:splat"  # Ensures dynamic routing to static files in the calculator folder
  status = 200

[[redirects]]
  from = "/weather/*"
  to = "/weather/:splat"  # Ensures dynamic routing to static files in the weather folder
  status = 200