[build]
  command = "python manage.py migrate && python manage.py collectstatic --noinput"  # Run migrations and collect static files
  publish = "."  # Publish the root directory of your project

# Redirects settings for routing requests to static files
[[redirects]]
  from = "/calculator/*"
  to = "/calculator/index.html"
  status = 200

[[redirects]]
  from = "/weather/*"
  to = "/weather/index.html"
  status = 200
