[build]
  command = "python manage.py migrate && python manage.py collectstatic --noinput"  # Run migrations and collect static files
  publish = "staticfiles"  # Publish collected static files to the `staticfiles` folder

# Redirects settings for routing requests to static files
[[redirects]]
  from = "/calculator/*"
  to = "/calculator/index.html"  # Ensure this path matches the static location
  status = 200

[[redirects]]
  from = "/weather/*"
  to = "/weather/index.html"  # Ensure this path matches the static location
  status = 200