[build]
  command = "python manage.py migrate && python manage.py collectstatic --noinput"  # Run migrations and collect static files
  publish = "staticfiles"  # Publish collected static files to the `staticfiles` folder

# Redirects settings for routing requests to static files
[[redirects]]
  from = "/calculator/*"
  to = "/static/calculator/index.html"  # Ensure it points to the correct static path
  status = 200

[[redirects]]
  from = "/weather/*"
  to = "/static/weather/index.html"  # Ensure it points to the correct static path
  status = 200
